# Generated by Django 2.2.6 on 2019-10-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3objects',
            name='file',
        ),
    ]
