# Generated by Django 2.2.6 on 2019-10-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0002_remove_s3objects_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3objects',
            old_name='uuid',
            new_name='uuidField',
        ),
    ]
