# Generated by Django 2.2.6 on 2019-10-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0003_auto_20191009_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3objects',
            old_name='uuidField',
            new_name='id',
        ),
    ]
