# Generated by Django 2.2.6 on 2019-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0004_auto_20191009_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3objects',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
