# Generated by Django 2.2.6 on 2019-10-12 08:35

from django.db import migrations, models
import s3objects.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0005_s3objects_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3objects',
            name='file',
            field=models.FileField(upload_to=s3objects.models.update_filename),
        ),
    ]
