# Generated by Django 2.2.6 on 2019-10-13 04:59

from django.db import migrations, models
import s3objects.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3objects', '0006_auto_20191012_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3objects',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='s3objects',
            name='file',
            field=models.FileField(upload_to=s3objects.models.update_filename, validators=[s3objects.models.validate_file_size]),
        ),
    ]
